### ISSUE TITLE
crash on tomcat 8

### ISSUE THREAD

**Issue by leantony** [andreacomo/tomcat-jwt-security#1]
Hi. I've followed all the steps in readme.md, but am still unable to run my app. This is the stacktrace

![screencapture-localhost-8080-public-index-html-1447273561374](https://cloud.githubusercontent.com/assets/7967272/11102110/b0cb62b8-88cb-11e5-820f-fa3fbc74ad43.png)

**Comment by andreacomo** [comment]
Hi! Which version of Tomcat are you using? I'm using Tomcat 7. Looks like a method is missing in your Tomcat version. I'd like to reproduce this error and fix it.

**Comment by andreacomo** [comment]
Created a new major release, just published to Maven Central (will be available soon). Now should work on Tomcat 8
