### ISSUE TITLE
Licence in pom.xml does not match LICENSE.md or project license

### ISSUE THREAD

**Issue by DaWalker** [andreacomo/tomcat-jwt-security#4]
pom.xml says Apache 2.0, everything else says MIT.

**Comment by DaWalker** [comment]
Also, tomcat-7 branch doesn't have a LICENSE file -- should I assume Apache 2.0 or MIT?

**Comment by andreacomo** [comment]
License aligned in pom and in tomcat-7 branch, now all is MIT
