### ISSUE TITLE
RFC: Update java-jwt to latest version 3.8.1

### ISSUE THREAD

**Issue by garnesen** [andreacomo/tomcat-jwt-security#8]
# Summary

Update [java-jwt](https://github.com/auth0/java-jwt) to [3.8.1](https://github.com/auth0/java-jwt/releases/tag/3.8.1)
# Motivation

- We would like to use this library for JWT authentication on our Tomcat server and we would like to use java-jwt to read custom claims, but the latest version is incompatible with 2.3.0
- 3.8.1 uses a cleaner API and could possibly eliminate the need for the `JwtTokenBuilder` and `JwtTokenVerifier` classes
- 3.8.1 fixes security issues and has performance enhancements
- java-jwt v2.x.x was last updated over two years ago

# Detailed design

### Break Backwards Compatibility
The latest version of java-jwt includes an easy to use builder to do token creation and verification. You can verify a token with:
```java
JWTVerifier verifier = JWT.require(Algorithm.HMAC256(secret)).build();
verifier.verify(token);
```
[example](https://github.com/auth0/java-jwt#verify-a-token)

And you can similarly create a token with [`JWT.create()`](https://github.com/auth0/java-jwt#create-and-sign-a-token). This means `JWTTokenBuilder` and `JWTTokenVerifier` could be removed.

### Keeping Backwards Compatibility
If you wish to keep the latest version backwards compatible with the existing APIs, then a bit more work would need to be done. 

**`JwtTokenVerifier`**
Internally it would still hold an instance of `com.auth0.jwt.JWTVerifier`, but the API has changed. It would be initialized with `JWT.require(Algorithm.HMAC256(secret)).build();`. The method `JWTVerifier.verify(token)` now returns a `DecodedJWT` object instead of `Map<String, Object>`. The `DecodedJWT` object gives access to claims.

**`JwtTokenBuilder`**
`JWTSigner` and `Options` classes no longer exist. This means `JwtTokenBuilder` would need to store the options itself, and then apply them when the `build` functions is called. Using the new `JWT.create()` tool, it could look something like this:
```java
public String build() {
        JWTCreator.Builder jwtBuilder = JWT.create();
	Calendar calendar = Calendar.getInstance();
	Date currentDate = new Date();
	if (issuedAt) {
		jwtBuilder.withIssuedAt(currentDate);
	}
	if (expirySeconds != null) {
		calendar.setTime(currentDate);
		calendar.add(Calendar.SECOND, expirySeconds);
		jwtBuilder.withExpiresAt(calendar.getTime());
	}
	if (jwtId) {
		jwtBuilder.withJWTId(UUID.randomUUID().toString());
	}
	if (notValidBeforeLeeway != null) {
		calendar.setTime(currentDate);
		calendar.add(Calendar.SECOND, -1 * notValidBeforeLeeway);
		jwtBuilder.withNotBefore(calendar.getTime());
	}
	return jwtBuilder.sign(algorithm);
}
```

# Drawbacks

### Break Backwards Compatibility

Self explanatory, current users of the library may need to update a significant portion of their code.

### Keeping Backwards Compatibility

Could be a pain to fit the current design of `tomcat-jwt-security` to fit around 3.8.1

# Adoption strategy

If backwards compatibility is broken, create a new major version so people know.

# Implementation

I would like to contribute to this project if an agreement can be made on updating to the latest version of `java-jwt` 😃

**Comment by andreacomo** [comment]
Hi and thank you for your proposition! I updated the library and code as you suggested, would you like to review or try it?
I made a pull request (#9) and I'll keep it open during the week for further test.

Please note that java-jwt now needs 2 more dependencies, I updated readme file with such information

**Comment by garnesen** [comment]
Awesome! I will take a look at the PR and try out the changes.

**Comment by andreacomo** [comment]
New version [2.3.0](https://repo1.maven.org/maven2/it/cosenonjaviste/tomcat-jwt-security/2.3.0/tomcat-jwt-security-2.3.0.jar) released on Maven central
